apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: BStage
  annotations:
    github.com/project-slug: abhishek25cse/BStage
spec:
  type: other
  lifecycle: unknown
  owner: abhishek25cse
